### ISSUE TITLE
dependent of GTK

### ISSUE THREAD

**Issue by mordonez** [joedicastro/lftp-mirror#2]
It's not possible use lftp-mirror without X

TypeError: Notify.Notification.set_icon_from_pixbuf() argument 1 must be gtk.gdk.Pixbuf, not None

**Comment by joedicastro** [comment]
Well, I've to confess, when I used to run this script in servers without X a long ago (now, always use rsync), I ran a different version without the `libnotify` stuff. But you're right, it's a nonsense to work with two different versions.

Now it's solved in 5e35cbc, if the script runs outside a X session, the notifications are disabled.

BTW, if you want to run this script under a X session with a user not logged in (as in a cron task), and yet you want to display the notifications, you can always export the `DISPLAY` environment variable before the actual command. For example, you want to run this periodically in a cron task, with the `cron` user and yet see the notifications. You can do this in this way, adding a similar line to the crontab:

``` bash
50 * * * * export DISPLAY=:0;cd ~/the/script/dir/;./lftp_mirror.py cfg sample.cfg 2>> ~/cron.log
```

And thank you for reporting the issues.

Best Regards
